[versions]
coreSplashscreen = "1.0.1"
jbcrypt = "0.4"
kotlin = "2.0.21"
monitor = "1.7.2"
junitKtx = "1.2.1"
kotlinGradlePlugin = "2.1.21"
detekt = "1.23.8"
detektFormatting = "1.23.0"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
detekt-formatting = {module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektFormatting"}
[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }